services:

  microservices:
    container_name: microservices
    command: bash
    build:
        context: .
        dockerfile: Dockerfile
    image: sfl/large-scale-system

  web:
    container_name: web
    image: sfl/large-scale-system
    command: web
    env_file: .env
    ports:
      - 8080:8080

  serviceOne:
    container_name: serviceOne
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    ports:
      - 8001:8080

  serviceTwo:
    container_name: serviceTwo
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    ports:
      - 8002:8080

  serviceTre:
    container_name: serviceTre
    image: sfl/large-scale-system
    command: serviceTre
    env_file: .env
    ports:
      - 8003:8080