services:

  microservices:
    container_name: microservices
    command: bash
    build:
        context: .
        dockerfile: services.Dockerfile
    image: sfl/large-scale-system

  lb:
    container_name: lb
    build:
        context: docker/
        dockerfile: lb.Dockerfile
    env_file: .env
    ports:
      - 80
      - 8080:80

  web-1:
    container_name: web-1
    image: sfl/large-scale-system
    command: web
    env_file: .env
    ports:
      - 8080
  web-2:
    container_name: web-2
    image: sfl/large-scale-system
    command: web
    env_file: .env
    ports:
      - 8080


  gateway:
    container_name: gateway
    build:
        context: docker/
        dockerfile: gateway.Dockerfile
    env_file: .env
    ports:
      - 80

  serviceOne:
    container_name: serviceOne
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    ports:
      - 8080

  serviceTwo:
    container_name: serviceTwo
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    ports:
      - 8080

  serviceTre:
    container_name: serviceTre
    image: sfl/large-scale-system
    command: serviceTre
    env_file: .env
    ports:
      - 8080