volumes:
  persistent-data:
    driver: local

services:

  microservices:
    build: .
    image: sfl/large-scale-system

  fluentd:
    image: fluentd:latest
    volumes:
      - ./docker/fluentd:/fluentd/etc/
    expose: [24224]
    ports: [24224:24224]

  lb:
    build: docker/lb
    env_file: .env
    expose: [80]
    ports: [8080:80]
    depends_on: [fluentd]
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: lb

  web-1:
    image: sfl/large-scale-system
    command: web
    env_file: .env
    expose: [8080]
    depends_on: [fluentd]
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: web-1

  web-2:
    image: sfl/large-scale-system
    command: web
    env_file: .env
    expose: [8080]
    depends_on: [fluentd]
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: web-2

  gateway:
    build: docker/gateway
    env_file: .env
    expose: [80]

  serviceOne:
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    expose: [8080]

  serviceTwo:
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    expose: [8080]

  serviceTre:
    image: sfl/large-scale-system
    command: serviceTre
    env_file: .env
    expose: [8080]
