services:

  microservices:
    command: bash
    build:
        context: .
        dockerfile: Dockerfile
    image: sfl/large-scale-system

  # web:
  #   image: sfl/large-scale-system
  #   command: web
  #   env_file: .env
  #   ports:
  #     - 8000:8080

  serviceOne:
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    ports:
      - 8001:8080

  serviceTwo:
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    ports:
      - 8002:8080

  serviceThree:
    image: sfl/large-scale-system
    command: serviceThree
    env_file: .env
    ports:
      - 8003:8080