services:

  gateway:
    build: ../gateway
    env_file: .env
    expose:
      - 80
    networks:
      - large-scale-system
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: serviceOne

  serviceOne:
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    expose: 
      - 8080
    networks:
      - large-scale-system
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: serviceOne

  serviceTwo:
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    expose: 
      - 8080
    networks: 
      - large-scale-system
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: serviceTwo

  serviceTre:
    image: sfl/large-scale-system
    command: serviceTre
    env_file: .env
    expose:
      - 8080
    networks:
      - large-scale-system
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: serviceTre
