# Configuration
@ServiceOne = http://localhost:8001
@ServiceTwo = http://localhost:8002
@ServiceTre = http://localhost:8003

GET http://localhost:80/serviceOne

### Main
GET {{ServiceOne}}
### Main
GET {{ServiceTwo}}
### Main
GET {{ServiceTre}}


### Health
GET {{ServiceOne}}/health
### Health
GET {{ServiceTwo}}/health
### Health
GET {{ServiceTre}}/health

### Info
GET {{ServiceOne}}/info
### Info
GET {{ServiceTwo}}/info
### Info
GET {{ServiceTre}}/info
