services:

  gateway:
    build: ../docker/gateway
    env_file: .env
    expose:
      - 80
    networks:
      - large-scale-system

  serviceOne:
    image: sfl/large-scale-system
    command: serviceOne
    env_file: .env
    expose: 
      - 8080
    networks:
      - large-scale-system

  serviceTwo:
    image: sfl/large-scale-system
    command: serviceTwo
    env_file: .env
    expose: 
      - 8080
    networks: 
      - large-scale-system

  serviceTre:
    image: sfl/large-scale-system
    command: serviceTre
    env_file: .env
    expose:
      - 8080
    networks:
      - large-scale-system
