services:

  lb:
    build: ../docker/lb
    env_file: .env
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - fluentd
    networks:
      - large-scale-system
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: lb

  web-1:
    image: sfl/large-scale-system
    command: web
    env_file: .env
    expose:
      - 8080
    depends_on:
      - fluentd
    networks:
      - large-scale-system
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: web-1

  web-2:
    image: sfl/large-scale-system
    command: web
    env_file: .env
    expose:
      - 8080
    depends_on:
      - fluentd
    networks:
      - large-scale-system
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: web-2