services:

  fluentd:
    image: fluentd:latest
    volumes:
      - ./../docker/fluentd:/fluentd/etc/
    expose:
      - 24224
    ports:
      - 24224:24224
    networks:
      - large-scale-system